# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol  = "[➜](bold red)"

[[battery.display]]
threshold = 40

[directory]
truncation_length = 10

[jobs]
format = "[$symbol $number\n]($style)"

[sudo]
disabled = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
symbol = " "
disabled = true

[python]
disabled = false
detect_extensions = []
detect_files = []

[docker_context]
disabled = false
symbol = " "

[java]
disabled = true
symbol = " "

[perl]
disabled = true

[nodejs]
disabled = true

[c]
disabled = true

# [conda]
# symbol = " "

# [dart]
# symbol = " "

# [elixir]
# symbol = " "

# [elm]
# symbol = " "

# [git_branch]
# symbol = " "

# [golang]
# symbol = " "

# [hg_branch]
# symbol = " "

# [julia]
# symbol = " "

# [nim]
# symbol = " "

# [nix_shell]
# symbol = " "

# [nodejs]
# symbol = " "

# [package]
# symbol = " "

# [perl]
# symbol = " "

# [php]
# symbol = " "

# [python]
# symbol = " "

# [ruby]
# symbol = " "

# [rust]
# symbol = " "

# [swift]
# symbol = "ﯣ "
